name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag Docker images
        run: |
          docker build  -t reverse-proxy:$GITHUB_SHA -f ./reverse-proxy/Dockerfile ./reverse-proxy
          docker tag reverse-proxy:$GITHUB_SHA jamessimonsdd/reverseproxy:latest
          docker push jamessimonsdd/reverseproxy:latest

          docker build  -t udagram-frontend:$GITHUB_SHA -f ./udagram-frontend/Dockerfile ./udagram-frontend
          docker tag udagram-frontend:$GITHUB_SHA jamessimonsdd/udagram-frontend:latest
          docker push jamessimonsdd/udagram-frontend:latest

          docker build  -t feed-service:$GITHUB_SHA -f ./feed-service/Dockerfile ./feed-service
          docker tag feed-service:$GITHUB_SHA jamessimonsdd/udagram-api-feed:latest
          docker push jamessimonsdd/udagram-api-feed:latest

          docker build  -t user-service:$GITHUB_SHA -f ./user-service/Dockerfile ./user-service
          docker tag user-service:$GITHUB_SHA jamessimonsdd/udagram-api-user:latest
          docker push jamessimonsdd/udagram-api-user:latest
